//
//  Copyright © 2026 Jesús Alfredo Hernández Alarcón. All rights reserved.
//

@testable import JourneyEvents
import Testing

@Suite("JourneyStep Tests")
struct JourneyStepTests {
    @Test("Init creates step with name and auto-generated timestamp")
    func init_createsStepWithNameAndAutoGeneratedTimestamp() {
        let step = JourneyStep(name: "app_started")

        #expect(step.name == "app_started")
        #expect(step.parameters.isEmpty)
        #expect(step.timestamp > 0)
    }

    @Test("Init creates step with parameters dictionary")
    func init_createsStepWithParametersDictionary() {
        let params: [String: AnyHashableSendable] = [
            "id": "line_1",
            "count": 42,
            "premium": true,
            "rating": 4.5,
        ]

        let step = JourneyStep(name: "line_viewed", parameters: params)

        #expect(step.name == "line_viewed")
        #expect(step.parameters.count == 4)
        #expect(step.parameters["id"]?.value(as: String.self) == "line_1")
        #expect(step.parameters["count"]?.value(as: Int.self) == 42)
        #expect(step.parameters["premium"]?.value(as: Bool.self) == true)
        #expect(step.parameters["rating"]?.value(as: Double.self) == 4.5)
    }

    @Test("Init creates step with custom timestamp")
    func init_createsStepWithCustomTimestamp() {
        let customTimestamp: Int64 = 1_234_567_890_000
        let step = JourneyStep(
            name: "custom_step",
            timestamp: customTimestamp,
        )

        #expect(step.timestamp == customTimestamp)
    }

    @Test("Equatable returns true when steps have same values")
    func equatable_returnsTrueWhenStepsHaveSameValues() {
        let timestamp: Int64 = 1000
        let params: [String: AnyHashableSendable] = ["id": "123"]

        let step1 = JourneyStep(name: "test", parameters: params, timestamp: timestamp)
        let step2 = JourneyStep(name: "test", parameters: params, timestamp: timestamp)

        #expect(step1 == step2)
    }

    @Test("Equatable returns false when steps have different names")
    func equatable_returnsFalseWhenStepsHaveDifferentNames() {
        let timestamp: Int64 = 1000
        let step1 = JourneyStep(name: "step1", timestamp: timestamp)
        let step2 = JourneyStep(name: "step2", timestamp: timestamp)

        #expect(step1 != step2)
    }
}

@Suite("AnyHashableSendable Tests")
struct AnyHashableSendableTests {
    @Test("Init wraps string and value returns correct type")
    func init_wrapsStringAndValueReturnsCorrectType() {
        let value = AnyHashableSendable("hello")

        #expect(value.value(as: String.self) == "hello")
        #expect(value.value(as: Int.self) == nil)
    }

    @Test("Init wraps integer and value returns correct type")
    func init_wrapsIntegerAndValueReturnsCorrectType() {
        let value = AnyHashableSendable(42)

        #expect(value.value(as: Int.self) == 42)
        #expect(value.value(as: String.self) == nil)
    }

    @Test("Init wraps boolean and value returns correct type")
    func init_wrapsBooleanAndValueReturnsCorrectType() {
        let value = AnyHashableSendable(true)

        #expect(value.value(as: Bool.self) == true)
        #expect(value.value(as: Int.self) == nil)
    }

    @Test("Init wraps double and value returns correct type")
    func init_wrapsDoubleAndValueReturnsCorrectType() {
        let value = AnyHashableSendable(3.14)

        #expect(value.value(as: Double.self) == 3.14)
        #expect(value.value(as: Int.self) == nil)
    }

    @Test("ExpressibleByStringLiteral creates value from string")
    func expressibleByStringLiteral_createsValueFromString() {
        let value: AnyHashableSendable = "test"

        #expect(value.value(as: String.self) == "test")
    }

    @Test("ExpressibleByIntegerLiteral creates value from integer")
    func expressibleByIntegerLiteral_createsValueFromInteger() {
        let value: AnyHashableSendable = 100

        #expect(value.value(as: Int.self) == 100)
    }

    @Test("ExpressibleByBooleanLiteral creates value from boolean")
    func expressibleByBooleanLiteral_createsValueFromBoolean() {
        let value: AnyHashableSendable = false

        #expect(value.value(as: Bool.self) == false)
    }

    @Test("ExpressibleByFloatLiteral creates value from float")
    func expressibleByFloatLiteral_createsValueFromFloat() {
        let value: AnyHashableSendable = 2.5

        #expect(value.value(as: Double.self) == 2.5)
    }

    @Test("Hashable and Equatable conform correctly for values")
    func hashableAndEquatable_conformCorrectlyForValues() {
        let value1 = AnyHashableSendable("test")
        let value2 = AnyHashableSendable("test")
        let value3 = AnyHashableSendable("different")

        #expect(value1 == value2)
        #expect(value1 != value3)

        var set = Set<AnyHashableSendable>()
        set.insert(value1)
        set.insert(value2)

        #expect(set.count == 1)
    }

    @Test("Description returns string representation of wrapped value")
    func description_returnsStringRepresentationOfWrappedValue() {
        #expect(AnyHashableSendable("hello").description == "hello")
        #expect(AnyHashableSendable(42).description == "42")
        #expect(AnyHashableSendable(true).description == "true")
    }
}
